<!-- A div to contain the list of errors generated by JavaScript -->
<div id="errorList"></div>
<script src="<?=$webRoot?>/media/js/newError.js"></script>
<!-- Header for logged in users -->
<div class="header" data-logged-in>
  <div class="header-padding">
<?php
// Include the logo
require_once "header.php";
?>
    <ul class="header-nav">
      <li class="header-item">
        <a href="<?=$webRoot?>/profile" class="icon-holder" title="Profile">
          <span class="icon icon-user" style="background-image: url('<?=$webRoot?>/media/img/anonymous.jpg')"></span>
        </a>
      </li>
      <li class="header-item">
        <!-- TODO: Make the following thingy open a notification box -->
        <span class="icon-holder" title="Notifications">
          <span class="icon icon-notif" data-src="<?=$webRoot?>/media/img/icon_notifications.png"></span>
        </span>
      </li>
      <!-- <li class="header-split"></li> -->
      <li class="header-item">
        <a href="<?=$webRoot?>/search" class="icon-holder" title="Find Roomies">
          <span class="icon icon-roomies"></span>
        </a>
      </li>
      <li class="header-item">
        <a href="#" class="icon-holder" title="Accommodation">
          <span class="icon icon-accomm"></span>
        </a>
      </li>
      <li class="header-item">
        <a href="<?=$webRoot?>/settings" class="icon-holder" title="Settings">
          <span class="icon icon-settings"></span>
        </a>
      </li>
      <li class="header-item">
        <a href="<?=$webRoot?>?logout" class="icon-holder" title="Sign out">
          <span class="icon icon-logout"></span>
        </a>
      </li>
    </ul>
  </div>
</div>
<!-- Space for the header -->
<div class="header-space"></div>
<!-- Main content -->
<div class="main">
<?php
// Welcome back message.
if (JUST_LOGGED_IN)
{
?>
  <div class="not-mobile banner">
    <header>
      <h1 class="h1">Welcome back, <?=$user->getFirstName()?>!</h1>
      <?php
      // TODO:
      // SELECT * FROM  [message table]
      //          WHERE the recipient is this user AND unread = true
      // If rowCount > 0, then output the following:
      // <p class="text">You have [rowCount] unread messages.</p>

      // TODO:
      // SELECT * FROM  [conexion table]
      //          WHERE the recipient is this user AND status is awaiting approval
      // If rowCount > 0, then output the following:
      // <p class="text">You have [rowCount] friend requests.</p>
      ?>
    </header>
  </div>
<?php
} // if
?>
