<!-- A div to contain the list of errors generated by JavaScript -->
<div id="errorList"></div>
<script src="<?=$webRoot?>/media/js/newError.js"></script>
<!-- Header for logged in users -->
<div class="header">
  <!-- <div class="header-padding">
    <div class="header-div">
    </div>
    <div class="header-div logo"> -->
<?php
// Include the logo
require_once "header.php";
?>
    <!-- </div>
    <div class="header-div">
      <ul class="ul header-menu" style="height:auto;">
      <li class="li">
        <a class="a" href="<?=$webRoot?>/profile/" title="My profile"><?=$user->getIdentifier('username')?></a>
      </li>
      <li class="li">
        <a class="a settings door" href="?logout=yes" title="Logout"></a>
      </li>
      <li class="li">
        <a class="a settings cog" href="<?=$webRoot?>/settings/" title="Account Settings"></a>
      </li>
    </ul>
    </div>
  </div> -->
</div>
<!-- Space for the header -->
<div class="header-space"></div>
<!-- Main content -->
<div class="main">
<?php
// Welcome back message.
if (JUST_LOGGED_IN)
{
?>
  <div class="not-mobile banner">
    <header>
      <h1 class="h1">Welcome back, <?=$user->getFirstName()?>!</h1>
      <?php
      // TODO:
      // SELECT * FROM  [message table]
      //          WHERE the recipient is this user AND unread = true
      // If rowCount > 0, then output the following:
      // <p class="text">You have [rowCount] unread messages.</p>

      // TODO:
      // SELECT * FROM  [conexion table]
      //          WHERE the recipient is this user AND status is awaiting approval
      // If rowCount > 0, then output the following:
      // <p class="text">You have [rowCount] friend requests.</p>
      ?>
    </header>
  </div>
<?php
} // if
?>
