<!-- A div to contain the list of errors generated by JavaScript -->
<div id="errorList"></div>
<!-- newError function -->
<script>(function(g){var d=g.document,l=d.getElementById('errorList'),n=function(m,t){var b=d.createElement('div');b.className='box errorBox ';b.innerHTML=m;l.appendChild(b);t=t||5000;setTimeout(function(){l.removeChild(b)},t)};g.newError=n}(window))</script>
<!-- Logo -->
<a href="<?=$webRoot?>" class="logo-link" title="Home">
	<img src="<?=$webRoot?>/media/img/logo.svg" alt="Roomies" class="logo-img">
</a>