<!-- A div to contain the list of errors generated by JavaScript -->
<div id="errorList"></div>
<!-- global functions -->
<script>(function(g){var d=g.document,l=d.getElementById("errorList"),c=0,s;g.newError=function(m){s="error_"+(c++);l.innerHTML+="<div class='box errorBox' id='"+s+"'><div class='errorX' data-delete='"+s+"'></div>"+m+"</div>"};g.rCookie={set:function(k,v,e,p,u,s){return(!k||/^(?:expires|max\-age|path|domain|secure)$/i.test(k))?!1:(d.cookie=encodeURIComponent(k)+"="+encodeURIComponent(v)+(e?(e.constructor===Number?(e===Infinity?"; expires=Fri, 31 Dec 9999 23:59:59 GMT":"; max-age="+e):e.constructor===String?("; expires="+e):e.constructor===Date?("; expires="+e.toUTCString()):""):"")+(u?"; domain="+u:"")+(p?"; path="+p:"")+(s?"; secure":""),!0)},get:function(k){return k?decodeURIComponent(d.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(k).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1")):null},has:function(k){return !!k&&(new RegExp("(?:^|;\\s*)"+encodeURIComponent(k).replace(/[\-\.\+\*]/g, "\\$&")+"\\s*\\=")).test(d.cookie)},remove:function(k,p,u){return this.has(k)&&this.set(k,'',new Date(0),p,u)}}}(window))</script>
<!-- Logo -->
<a href="<?=$webRoot?>" class="logo-link" title="Home">
	<img src="<?=$webRoot?>/media/img/logo.svg" alt="Roomies" class="logo-img">
</a>