<!-- A div to contain the list of errors generated by JavaScript -->
<div id="errorList"></div>
<script src="<?=$webRoot?>/media/js/newError.js"></script>
<!-- Header for logged out users -->
<div class="header">
  <?php require_once "header.php"; ?>
</div>
<!-- Space for the header -->
<div class="header-space"></div>
<!-- Main content -->
<div class="main">